### ISSUE TITLE
history/addon/history/lmo-history.php

### ISSUE THREAD

**Issue by henshingly** [dwblmo/LMO_Addons#1]
Zeile 103
`if (basename($_SERVER['PHP_SELF'])=="lmo-history_new.php") {?>`
da scheint Dir beim testen/updaten der "alten" Dateien ein Fehler reingeruscht zu sein.
 Es ist nämlich die `lmo-history.php` und keine andere Datei gemeint.

Gruß Henshingly

**Comment by babbisch** [comment]
Danke, Fix mit 0d2b47b9684075767110a5ae2a35abcf1eee4722
